sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: wG1yuoBvMjSO97op8NtPEJ94Gp1VgLaym8i+dSagXk1MPBbCAAd+c+pBya8H9KCNIRZtCM6AJHmng2o3VP8UMgI4Ml9mz0simwAuJk+WDkYme/mduYtRWPxg2CBjTzO28tHfEi0p6WzVdgtj1lhc6Rk3Ih1aDbTCInpeKbdu5Txu+X2iBj0aNEox4Wsl3xe3sPuB+A2m7LlHEo+PBPqeYgfDU9fSDIpiVaqeIi0/004a2dkv2aLTXGo3BL9n04waOip1lciZ4bK9DCJGkYZFgtwL3OCRNA+scexwSx+Txsu/jQaHUuDY1HDWN870eLZI3IYPBYu+S1B/UA7a2vT5q02G1w2iy9YYyeKoCDYBlmqkgSidBLCDP9yBNDayEkAs4W0fd3BZKsHNFZc0V73zUheb6qeB1qHIX0cfzHmoZbQYOYPRL+q93dypXMkmk/rlfr5bwfHpdcRI0IVhIHi/Ri8PP6n1ipsfDb6FNqBGolHcKT6VQqbq8fKJb89ggiBEBFLNQ2CecltaEiG35slV/cROssg2ccBwMADlH1ROENBy5kF12DxgKXkrTioU3KJsF3R5YBjIBf8x58gUVRYyb0WnyR5g7LjDQue396AXwGH68T6XSDE8AyizsaG1Z1N4O3T69NGdVz52UTfK9dTFYPSMdRd92OJYSTn3ZFLXoXM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Howards-End_2891
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy